site_name: The Self-Hosted Book
site_url: https://ajfriesen.github.io/self-hosted-book-website/
site_author: Andrej Friesen
site_description: >-
  Landing page for the self-hosted book + additional resources

repo_url: https://github.com/ajfriesen/self-hosted-book-website

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.share
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # primary: blue grey
      # accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # custom_dir: docs/overrides
  font:
    text: Roboto

  palette:
    primary: black

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - social
  - search

extra:
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

  social:
    - icon: fontawesome/solid/blog
      link: https://ajfriesen.com
      name: Blog
    - icon: fontawesome/brands/github
      link: https://github.com/ajfriesen/
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://www.ajfriesen.com/
      name: Twitter
    - icon: fontawesome/brands/mastodon 
      link: ajfriesen.com
      name: Mastodon
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/andrej-friesen/
      name: LiknkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mr_ajfriesen/?ref=ajfriesen.com
      name: Instagram
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/ajfriesen
      name: Reddit

copyright: Copyright &copy; 2023 Andrej Friesen